[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.1
blur = true

option_as_alt = "Both"

[font]
normal.family = "D2CodingLigature Nerd Font"

size = 20

[keyboard]
bindings = [
{ key = "W", mods = "Command", action = "None" },
{ key = "Q", mods = "Command", action = "None" }
]

