[mgr]

prepend_keymap = [
	{ on = [ "q" ], run = 'close', desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "<C-q>" ], run = 'quit', desc = "Exit the process" },
# goto
	{ on = [ "g", "d" ],       run = "cd ~/Desktop",   desc = "Go ~/Desktop" },
  { on = [ "g", "l" ],       run = "cd ~/Downloads",   desc = "Go ~/Downloads" },
]
